baseURL = "/"
languageCode = "en-us"
title = "Creations"
copyright = "© Pranav B"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=11 # articles per page

[params]
	mode="light" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "This website is designed so as to reduce its digital industry ecological footprint. Each page sits at an average of 865kb. "

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pranavb104"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/pranavb104/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/pranavb104/"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Writings"
url = "/writings"
weight = 3
